kind: Deployment
apiVersion: apps/v1
metadata:
  name: valueservice
spec:
  selector:
    matchLabels:
      app: valueservice
  replicas: 2 
  template: 
    metadata:
      labels:
        app: valueservice
        version: v1
    spec:
      containers:
      - name: valueservice
        image: eshneken/valueservice:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
 name: valueservice
spec:
 type: NodePort
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: valueservice