kind: Deployment
apiVersion: apps/v1
metadata:
  name: valueservice
spec:
  selector:
    matchLabels:
      app: valueservice
  replicas: 1
  template: 
    metadata:
      labels:
        app: valueservice
        version: v1
    spec:
      containers:
      - name: valueservice
        image: iad.ocir.io/orasenatdecaentegacpgut02/eshneken_ocir/valueservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: ocir
---
kind: Service
apiVersion: v1
metadata:
 name: valueservice
spec:
 type: NodePort
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: valueservice